# Site settings
title: "Jordan Armstrong Resume"
description: "Professional resume for Jordan Armstrong"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jordan Armstrong"
resume_title:                   "Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jordan@jordanarmstrong.net"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "724-506-3760"
resume_contact_address:         "1384 Summit Street Columbus Ohio"

resume_header_contact_info:     "1384 Summit Street Columbus OH • 724-506-3760 • jordan@jordanarmstrong.net"
display_header_contact_info:    "false"

resume_header_intro: <p>I am a highly engaged developer excited about the opportunity to bring my skills and passion to bear for your customers. I am comfortable working with the full stack and have a passion for CI/CD in order to bring immediate value to our customers with quick to market, iterative solutions.</p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_skills:          true
resume_section_projects:        false
resume_section_education:       true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/ramblingjordan"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/jordanphiliparmstrong"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://jordanarmstrong.net"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
